%macro _metautil_stop_if_error(operation_type, object_name, throw_exception_if_obj_not_found=1, rc_variable=rc);
	length error_message $ 256;
	
	%let operation_type = %lowcase(&operation_type.);
	
	%if &operation_type. = metadata_newobj %then %do;
		if &rc_variable. lt 0 then do;
			error_message = catx(" ", "error while creating metadata object &object_name.:", sysmsg());
			call symputx('error_message', error_message);
			stop;
		end;
	%end;
	%else %if &operation_type. = metadata_getnobj %then %do;
		if &rc_variable. lt 0 and &rc_variable. gt -4 then do;
			error_message = catx(" ", "error while searching metadata object &object_name.:", sysmsg());
			call symputx('error_message', error_message);
			stop;
		end;
		
		%if &throw_exception_if_obj_not_found. %then %do;
		else if &rc_variable. = 0 then do;
			error_message = catx(" ", "no object found with criteria &object_name. was found");
			call symputx('error_message', error_message);
			stop;
		end;
		else if &rc_variable. = -4 then do;
			error_message = catx(" ", "the index requested is higher then the number of objects that match the criteria &object_name.");
			call symputx('error_message', error_message);
			stop;
		end;
		%end;
	%end;
	%else %if &operation_type. = metadata_getnasn %then %do;
		if &rc_variable. lt 0 and &rc_variable. gt -4 then do;
			error_message = catx(" ", "error while getting association &object_name.:", sysmsg());
			call symputx('error_message', error_message);
			stop;
		end;
	%end;
	%else %if &operation_type. = metadata_setassn %then %do;
		if &rc_variable. lt 0 then do;
			error_message = catx(" ", "error while setting association &object_name.:", sysmsg());
			call symputx('error_message', error_message);
			stop;
		end;
	%end;
	%else %if &operation_type. = metadata_resolve %then %do;
		if &rc_variable. le 0 then do;
			error_message = catx(" ", "error while resolving object", &object_name., ":", sysmsg());
			call symputx('error_message', error_message);
			stop;
		end;
	%end;
	%else %if &operation_type. = metadata_setattr %then %do;
		if &rc_variable. lt 0 then do;
			error_message = catx(" ", "error while setting attribute", &object_name., ":", sysmsg());
			call symputx('error_message', error_message);
			stop;
		end;
	%end;
	%else %if &operation_type. = metadata_getattr %then %do;
		if &rc_variable. lt 0 then do;
			error_message = catx(" ", "error while getting attribute", &object_name., ":", sysmsg());
			call symputx('error_message', error_message);
			stop;
		end;
	%end;
	%else %if &operation_type. = metadata_getnatr %then %do;
		if &rc_variable. lt 0 and &rc_variable. gt -4 then do;
			error_message = catx(" ", "error while getting attribute with index ", &object_name., ":", sysmsg());
			call symputx('error_message', error_message);
			stop;
		end;
	%end;
	%else %if &operation_type. = metasec_getnauth %then %do;
		if &rc_variable. lt 0 and &rc_variable. ^= -5 then do;
			error_message = catx(" ", "error while getting permission with index ", &object_name., ":", sysmsg());
			call symputx('error_message', error_message);
			stop;
		end;
	%end;
	%else %if &operation_type. = metasec_setauth %then %do;
		if &rc_variable. ^= 0 then do;
			error_message = catx(" ", "error while setting permission ", &object_name., ":", sysmsg());
			call symputx('error_message', error_message);
			stop;
		end;
	%end;
	%else %if &operation_type. = metasec_remact %then %do;
		if &rc_variable. lt 0 then do;
			error_message = catx(" ", "error while removing ACT ", &object_name., ":", sysmsg());
			call symputx('error_message', error_message);
			stop;
		end;
	%end;
	%else %if &operation_type. = metasec_applyact %then %do;
		if &rc_variable. lt 0 then do;
			error_message = catx(" ", "error while applying ACT ", &object_name., ":", sysmsg());
			call symputx('error_message', error_message);
			stop;
		end;
	%end;
	%else %if &operation_type. = metasec_getnact %then %do;
		if &rc_variable. lt 0 and &rc_variable. ^= -5 then do;
			error_message = catx(" ", "error while getting ACT with index ", &object_name., ":", sysmsg());
			call symputx('error_message', error_message);
			stop;
		end;
	%end;
	
%mend _metautil_stop_if_error;